### PR TITLE
Closes #35: Adding ESLint.

### LINKED ISSUE #35: Better user feedback from config input.
Currently, not much feedback is given on the user supplied fields from the config input regarding which sensors to use. This could be improved.

### PR DESCRIPTION
**Pull request by amlinger**
This will help contributors of this repository adhere to a more similar style of code.

### CODE REVIEW

**Comment by jannylund** [comment]
I suggest using line length 120 instead of 80. I know 80 has long been considered a standard, but today it makes a lot more sense to allow 120 as screens are growing wider and wider. (and it's still a rather useful limit)

**Comment by jannylund** [comment]
Btw, you could consider adding a SonarQube analysis as well. Their hosted solution is free for opensource projects these days. (not sure how well it handles JS though). 

https://sonarqube.com/

**Comment by amlinger** [comment]
Regarding 120 chars per line instead of 80, definitely agree that is an old setting (that I might be clinging to for a bit too long). I might suggest a compromise of 100 for two reasons:
1. No need for horizontal scrolling on GitHub.
2. Readable PR:s on mobile.

I'm not at all familiar with SonarQube, thanks for the suggestion, I'll look it up.

**Comment by jannylund** [comment]
100 sounds fine. SonarQube is static analyses + linting + code coverage visualization, it takes a while to get it in your workflow but personally I like it very much. It has however shown a lot of false positives in the javascript projects I use it on, but I still think the value it brings is worth, even with manual marking of false positives.

**Comment by amlinger** [comment]
Close to the 1-year anniversary of this I think it is nice to get some closure on this. I've changed the line limit to 100.

SonarQube looks pretty interesting, but it is out of scope for this for now. If you are still interested in setting it up, I'd be interested in following that up. Thanks!

**Pull request merged**
